# Names of columns in the csv files
[names]
timestamp_column = "timestamp" # This column will be used for sorting and resampling
index_column = "index"
temperature_column = "temperature"

[formats]
time_format = "%Y-%m-%d %H:%M:%S" # see https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

[sorting]
enable = true
order = "descending" # or "ascending", default is "descending"